name: Deploy to GitHub Pages

# 仅在推送到 main 分支时触发
on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发 workflow
# 设置执行的工作
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 检查代码库
      - name: Checkout code
        uses: actions/checkout@v3

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          # 部署 dist 目录中的内容
          publish_dir: dist
